spring.application.name=library-member
server.port=8080

# main log level
logging.level.root=INFO

# package log level
logging.level.com.book.library=DEBUG

# spring log
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# make file
logging.file.name=logs/library-member-local.log
logging.file.path=logs