###################### default properties ######################
spring.application.name=library-member
server.port=8080
###################### default properties ######################
###################### database properties #####################
spring.datasource.url=jdbc:mysql://43.203.240.3:3306/library?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=library
spring.datasource.password=management1234!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
###################### database properties #####################
######################## log properties ########################
# main log level
logging.level.root=INFO

# package log level
logging.level.com.book.library=DEBUG

# spring log
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# make file
logging.file.name=logs/library-member-local.log
logging.file.path=logs
######################## log properties ########################