###################### default properties ######################
spring.application.name=library-frontend
server.port=6060
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
###################### default properties ######################
####################### domain properties ######################
library.book.url = http://localhost:7070
library.member.url = http://localhost:8080
library.rental.url = http://localhost:9090
####################### domain properties ######################
