// library-common - 도메인/DTO만 (순수 JDBC)

apply plugin: 'java-library'

dependencies {
    // 도메인/DTO에 필요한 최소 의존성만
    api 'com.fasterxml.jackson.core:jackson-annotations:2.16.0'
    api 'org.springframework:spring-context:6.1.1'
    api 'org.springframework:spring-jdbc:6.1.1'
    api 'org.springframework:spring-tx:6.1.1'
    api 'mysql:mysql-connector-java:8.0.33'
}
