plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.book.library'
version = '0.0.1-SNAPSHOT'
description = 'library-frontend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

springBoot {
    mainClass.set('com.book.library.frontend.LibraryFrontendApplication')
}

dependencies {
    implementation project(':library-common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.4.0'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
}
